# Generated by Django 5.0.6 on 2024-06-18 10:45

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Tags')),
                ('chain', models.CharField(max_length=30)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=35, null=True)),
                ('price', models.DecimalField(decimal_places=34, max_digits=64)),
                ('volume_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_btc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Change 24h')),
                ('votes', models.IntegerField(default=0)),
                ('votes24h', models.IntegerField(default=0)),
                ('market_cap_presale', models.BooleanField(default=False)),
                ('path_coin_img', models.CharField(max_length=255)),
                ('path_chain_img', models.CharField(max_length=255)),
                ('launch_date_str', models.CharField(blank=True, max_length=50, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('per_page', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
