# Generated by Django 5.0.6 on 2024-06-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usersettings_all_time_best_usersettings_audited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='item_sub_symbol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
