# Generated by Django 5.0.6 on 2024-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usersettings_item_sub_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='head_filter',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
