# Generated by Django 5.0.6 on 2024-06-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usersettings_head_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='head_filter',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
