# Generated by Django 5.0.6 on 2024-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_coin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
