# Generated by Django 5.0.6 on 2024-07-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_coin_contract_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='label',
            new_name='symbol',
        ),
    ]
