# Generated by Django 5.0.6 on 2024-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_label_coin_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reward', models.CharField(max_length=255)),
                ('path_coin_img', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
    ]
