# Generated by Django 5.0.6 on 2024-07-08 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_airdrops'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoted', to='app.coin')),
            ],
        ),
    ]
