# Generated by Django 5.0.6 on 2024-07-12 12:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_promotedcoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='coins_votes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Coins Votes'),
        ),
    ]
