# Generated by Django 5.0.6 on 2024-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usersettings_coins_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='selected_auto_voting',
            field=models.BooleanField(default=False),
        ),
    ]
