# Generated by Django 5.0.6 on 2024-07-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_coin_selected_auto_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='contract_address',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
