# Generated by Django 5.0.7 on 2024-07-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_coin_volume_btc_alter_coin_volume_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecoin',
            name='path_chain_img',
            field=models.ImageField(max_length=255, upload_to='chain_images/'),
        ),
        migrations.AlterField(
            model_name='basecoin',
            name='path_coin_img',
            field=models.ImageField(max_length=255, upload_to='coin_images/'),
        ),
    ]
