# Generated by Django 5.0.7 on 2024-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_basecoin_path_chain_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='theme_site',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
