# Generated by Django 5.0.7 on 2024-07-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='count_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
