# Generated by Django 5.0.7 on 2024-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_sitesettings_count_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('right-banner', 'Top Right Banner'), ('left-banner', 'Top Left Banner'), ('banner_1', 'Banner Bottom 1'), ('banner_2', 'Banner Bottom 2'), ('banner_3', 'Banner Bottom 3'), ('banner_4', 'Banner Bottom 4'), ('banner_5', 'Banner Bottom 5'), ('banner_6', 'Banner Bottom 6')], max_length=20)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reclam Banner',
                'verbose_name_plural': 'Reclam Banners',
            },
        ),
    ]
